services:
  backend1:
    image: luksa/kubia:latest
    networks:
      - my-network
  
  backend2:
    image: luksa/kubia:latest
    networks:
      - my-network
      
  mylb:
    #image: arm64v8/nginx
    image: nginx
    ports:
      - "80:80"  # Map port 80 on the host to port 80 in the container
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount local directory to container
    networks:
      - my-network

networks:
  my-network:
    name: my-network
    external: true
